### ISSUE TITLE
CPU issue

### ISSUE THREAD

**Issue by SeroMaster** [rwf93/Starbound#11]
Okay, just in theory, is it now possible to fix the fact that Starbound doesn't utilise more than 2 cores? Can this game finally become playable with mods?

**Comment by rwf93** [comment]
Maybe. Technically in theory it could possibly work, but a major problem would be synchronization. Especially in the context of lua; threaded or multicore lua states has been known to be painful to implement with it's functionality breaking a lot of things.

**Comment by jkotrc** [comment]
I'm not yet fully versed in the lua part of the game, but would it not be possible to implement/bugfix threading in C++, hiding it completely from the modding API?
