### ISSUE TITLE
Please create dev branch for next version

### ISSUE THREAD

**Issue by jkotrc** [rwf93/Starbound#12]
In order to maintain consistency with the source code as provided and future releases, I would argue for archiving the default state of the code in branch `v1.4.4`. 

I am interested in seeing a community update effort succeed and believe that some version management would go a long way. To this end I suggest a branch `v1.5.0-dev` for upcoming changes that will make up the next community-sourced major version. It remains to be seen how many changes count for a minor version and which count for major. Perhaps major versions should include collections of main requirements and minor for bug fixes. Ideally, each release should mention what changes were made

Pull requests coming soon-ish

**Comment by rwf93** [comment]
That sounds like a great idea! I've created a new branch with the initial commit of this repository which should be an unmodified leak of the game, as well as dev branch for the next community update.

Happy hacking!
