### ISSUE TITLE
Fix x86 build? (and/or for XP) :)

### ISSUE THREAD

**Issue by DartPower** [rwf93/Starbound#2]
Can you fix x86 build? (and/or for XP) :)

**Comment by rwf93** [comment]
I don't have any method right now of testing it for XP/x86, I might be able to look into it. If you can possibly figure it out you could fork it and open a PR. I'll most likely merge it.

**Comment by SweptWasTaken** [comment]
> Can you fix x86 build? (and/or for XP) :)

If you're still on x86 or XP you should update your hardware/OS and stop wasting people's time asking for compatibility with your woefully out of date system specs.

**Comment by rwf93** [comment]
Agreed. If you figure it out open a PR.

**Comment by DartPower** [comment]
Okay, but for example: I want to test it on Retro Laptop (e.g. for Windows 7 too) but can't compile it because scripts for x86 not adapted as yes with x64 

Also i want it test on Windows 10 x86 :/
