### ISSUE TITLE
starbound does not play sound when compiled against recent version of SDL2

### ISSUE THREAD

**Issue by dirbasti** [rwf93/Starbound#3]
starbound does not play sound when compiled against recent version of SDL2 (2.0.5 --> 2.28.3) while using SDL1 legacy functions SDL_OpenAudio() and SDL_PauseAudio(). Replacing them with SDL2 functions brings the sound back, see attachment. 
SDL_OpenAudio() --> SDL_OpenAudioDevice()
SDL_PauseAudio() --> SDL_PauseAudioDevice()

Tested under Win11 x64 with SDL 2.0.5 and 2.28.3.
[StarMainApplication_sdl.zip](https://github.com/rwf93/Starbound/files/12776484/StarMainApplication_sdl.zip)

**Comment by rwf93** [comment]
This seems to work for the latest commit of SDL2. I'd have also preferred if this was a pull request (you can fork, modify, and open), but this is fine.
Thank you for your contribution.
