### ISSUE TITLE
Is this illegal? Is this going to be worked on?

### ISSUE THREAD

**Issue by Shadowblitz16** [rwf93/Starbound#4]
Title.
There are some things I would love to see in starbound but.

**Comment by rwf93** [comment]
Yes, technically it's illegal in that it's using the source code leak. This repository does risk a DMCA take down, however, the developers of Starbound have mentioned that they don't particularly care about the source code leak. As for "Is this is going to be worked on?", That's more of a matter of my own interest and public interest. **I will try my best to accept PR's or issues**. If need be, I can also add people to the contributors list, or they can also fork it and work on their own repository.

**Comment by Shadowblitz16** [comment]
ok thankyou
